### ISSUE TITLE
Set an appropriate document title

### ISSUE THREAD

**Issue by funspectre** [EstherPhebe/ngbo-search#2]
The page title is currently set to "Show Info". I think using the project name "**ngbọ́**" or some variation of it—perhaps the stylization suggested in #1—will be more appropriate. This title may then be combined with subtitles using a separator e.g. "**ngbọ́ | Show Details**" or "**ngbọ́ · Show Details**".

**Comment by EstherPhebe** [comment]
@funspectre Thank you for taking the time. I have fixed this issue and included a page icon.
