### ISSUE TITLE
Pressing Enter in the search field reloads the page

### ISSUE THREAD

**Issue by funspectre** [EstherPhebe/ngbo-search#3]
When I enter a search query and press the enter key while still focused on the search field, the page reloads to a fresh copy of the page with URL like this: `https://estherphebe.github.io/ngbo-search/?search=bad`.

The expected behavior on pressing the enter key is for the search to be executed and the results be shown as if I pressed the search button.

**Comment by EstherPhebe** [comment]
This has been fixed, thank you for your feedback.
