### ISSUE TITLE
The search input field looks out of place.

### ISSUE THREAD

**Issue by funspectre** [EstherPhebe/ngbo-search#6]
The search input field is slightly—or more noticeably in some cases—larger than the buttons—clear and search—next to it. The field should be adjusted to have the same height as the buttons so that it lies flush with them.

![Search Field in Firefox](https://user-images.githubusercontent.com/5924650/107655205-a0d8a400-6c83-11eb-8b58-5056fc0a31ff.png)

![Search Field in Chrome](https://user-images.githubusercontent.com/5924650/107655144-8e5e6a80-6c83-11eb-8b86-9a7481359bf9.png)

**Comment by EstherPhebe** [comment]
Fixed this issue, thanks for your feedback
